/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopWorldcupRouteImport } from './routes/shop.worldcup'
import { Route as ShopRetroRouteImport } from './routes/shop.retro'
import { Route as ShopFootballRouteImport } from './routes/shop.football'
import { Route as ShopF1RouteImport } from './routes/shop.f1'
import { Route as ShopCricketRouteImport } from './routes/shop.cricket'
import { Route as ShopBasketballRouteImport } from './routes/shop.basketball'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as InfoPageRouteImport } from './routes/info.$page'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopWorldcupRoute = ShopWorldcupRouteImport.update({
  id: '/worldcup',
  path: '/worldcup',
  getParentRoute: () => ShopRoute,
} as any)
const ShopRetroRoute = ShopRetroRouteImport.update({
  id: '/retro',
  path: '/retro',
  getParentRoute: () => ShopRoute,
} as any)
const ShopFootballRoute = ShopFootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => ShopRoute,
} as any)
const ShopF1Route = ShopF1RouteImport.update({
  id: '/f1',
  path: '/f1',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCricketRoute = ShopCricketRouteImport.update({
  id: '/cricket',
  path: '/cricket',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBasketballRoute = ShopBasketballRouteImport.update({
  id: '/basketball',
  path: '/basketball',
  getParentRoute: () => ShopRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoPageRoute = InfoPageRouteImport.update({
  id: '/info/$page',
  path: '/info/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/info/$page': typeof InfoPageRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/basketball': typeof ShopBasketballRoute
  '/shop/cricket': typeof ShopCricketRoute
  '/shop/f1': typeof ShopF1Route
  '/shop/football': typeof ShopFootballRoute
  '/shop/retro': typeof ShopRetroRoute
  '/shop/worldcup': typeof ShopWorldcupRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/info/$page': typeof InfoPageRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/basketball': typeof ShopBasketballRoute
  '/shop/cricket': typeof ShopCricketRoute
  '/shop/f1': typeof ShopF1Route
  '/shop/football': typeof ShopFootballRoute
  '/shop/retro': typeof ShopRetroRoute
  '/shop/worldcup': typeof ShopWorldcupRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/info/$page': typeof InfoPageRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/basketball': typeof ShopBasketballRoute
  '/shop/cricket': typeof ShopCricketRoute
  '/shop/f1': typeof ShopF1Route
  '/shop/football': typeof ShopFootballRoute
  '/shop/retro': typeof ShopRetroRoute
  '/shop/worldcup': typeof ShopWorldcupRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/shop'
    | '/wishlist'
    | '/auth/callback'
    | '/info/$page'
    | '/product/$id'
    | '/shop/basketball'
    | '/shop/cricket'
    | '/shop/f1'
    | '/shop/football'
    | '/shop/retro'
    | '/shop/worldcup'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/wishlist'
    | '/auth/callback'
    | '/info/$page'
    | '/product/$id'
    | '/shop/basketball'
    | '/shop/cricket'
    | '/shop/f1'
    | '/shop/football'
    | '/shop/retro'
    | '/shop/worldcup'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/shop'
    | '/wishlist'
    | '/auth/callback'
    | '/info/$page'
    | '/product/$id'
    | '/shop/basketball'
    | '/shop/cricket'
    | '/shop/f1'
    | '/shop/football'
    | '/shop/retro'
    | '/shop/worldcup'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InfoPageRoute: typeof InfoPageRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/worldcup': {
      id: '/shop/worldcup'
      path: '/worldcup'
      fullPath: '/shop/worldcup'
      preLoaderRoute: typeof ShopWorldcupRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/retro': {
      id: '/shop/retro'
      path: '/retro'
      fullPath: '/shop/retro'
      preLoaderRoute: typeof ShopRetroRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/football': {
      id: '/shop/football'
      path: '/football'
      fullPath: '/shop/football'
      preLoaderRoute: typeof ShopFootballRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/f1': {
      id: '/shop/f1'
      path: '/f1'
      fullPath: '/shop/f1'
      preLoaderRoute: typeof ShopF1RouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cricket': {
      id: '/shop/cricket'
      path: '/cricket'
      fullPath: '/shop/cricket'
      preLoaderRoute: typeof ShopCricketRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/basketball': {
      id: '/shop/basketball'
      path: '/basketball'
      fullPath: '/shop/basketball'
      preLoaderRoute: typeof ShopBasketballRouteImport
      parentRoute: typeof ShopRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$page': {
      id: '/info/$page'
      path: '/info/$page'
      fullPath: '/info/$page'
      preLoaderRoute: typeof InfoPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteChildren {
  ShopBasketballRoute: typeof ShopBasketballRoute
  ShopCricketRoute: typeof ShopCricketRoute
  ShopF1Route: typeof ShopF1Route
  ShopFootballRoute: typeof ShopFootballRoute
  ShopRetroRoute: typeof ShopRetroRoute
  ShopWorldcupRoute: typeof ShopWorldcupRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopBasketballRoute: ShopBasketballRoute,
  ShopCricketRoute: ShopCricketRoute,
  ShopF1Route: ShopF1Route,
  ShopFootballRoute: ShopFootballRoute,
  ShopRetroRoute: ShopRetroRoute,
  ShopWorldcupRoute: ShopWorldcupRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRouteWithChildren,
  WishlistRoute: WishlistRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InfoPageRoute: InfoPageRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
