-- 1. DROP THE BROKEN TRIGGER THAT BLOCKS INSERTS
DROP TRIGGER IF EXISTS tr_order_stock ON orders;
DROP FUNCTION IF EXISTS handle_order_stock();

-- 2. ADD A DELETE POLICY SO OLD ORDERS CAN BE DELETED
CREATE POLICY "Orders Delete Policy" ON "public"."orders"
AS PERMISSIVE FOR DELETE
TO public
USING (true);
